# Generated by Django 4.2.3 on 2023-08-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('pg_rg_no', models.IntegerField(max_length=10)),
                ('pro_address', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('rent', models.IntegerField(max_length=50)),
                ('property_image1', models.ImageField(upload_to='property_images/')),
                ('property_image2', models.ImageField(upload_to='property_images/')),
                ('property_image3', models.ImageField(upload_to='property_images/')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('no_of_beds', models.IntegerField(max_length=50)),
                ('Amenities', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'addpg',
            },
        ),
    ]
