# Generated by Django 4.2.3 on 2023-08-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_pg_delete_addpg'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pg',
            table='PG',
        ),
    ]
