# Generated by Django 4.2.3 on 2023-08-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_alter_pg_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='property_image1',
            field=models.ImageField(upload_to='property_images1/'),
        ),
        migrations.AlterField(
            model_name='pg',
            name='property_image2',
            field=models.ImageField(upload_to='property_images2/'),
        ),
        migrations.AlterField(
            model_name='pg',
            name='property_image3',
            field=models.ImageField(upload_to='property_images3/'),
        ),
    ]
