# Generated by Django 4.2.3 on 2023-08-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0006_alter_pg_property_image1_alter_pg_property_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='no_of_beds',
            field=models.PositiveIntegerField(),
        ),
    ]
