# Generated by Django 4.2.3 on 2023-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0007_alter_pg_no_of_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='no_of_beds',
            field=models.CharField(max_length=1),
        ),
    ]
