# Generated by Django 4.2.3 on 2023-08-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0008_alter_pg_no_of_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGLister',
            fields=[
                ('unique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('emg_phone', models.CharField(max_length=20)),
                ('id_proof', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('security_answer', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'PGLister',
            },
        ),
    ]
