# Generated by Django 4.2.3 on 2023-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0009_pglister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('unique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('dob', models.DateField()),
                ('emg_no', models.IntegerField(max_length=10)),
                ('proof_ID', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=30)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
