# Generated by Django 4.2.3 on 2023-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0010_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_amount', models.IntegerField(max_length=10)),
                ('pgid', models.IntegerField()),
                ('pgname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BookDetails',
            },
        ),
    ]
