# Generated by Django 4.2.3 on 2023-08-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0011_bookdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookDetails',
        ),
    ]
