# Generated by Django 4.2.3 on 2023-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0013_bookdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
