# Generated by Django 4.2.3 on 2023-08-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0017_alter_pglister_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='pg_rg_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
