# Generated by Django 4.2.3 on 2023-08-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0018_alter_pg_pg_rg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='security_answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
