# Generated by Django 4.2.3 on 2023-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0019_customer_security_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='owner_uniq_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
